version: '3.8'
services:
  api:
    container_name: django_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - admin_db

  admin_db:
    container_name: django_admin_db
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: django_admin
      MYSQL_USER: root
      MSQL_PASSWORD: josanojp25
      MYSQl_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql